### ISSUE TITLE
Unhandled error from websocket

### ISSUE THREAD

**Issue by SaavdhaanCyber** [wildfoundry/dataplicity-agent#39]
Here is some info 

`02/Mar/2018 18:51:56]:agent:INFO: dataplicity 0.4.30a0
[02/Mar/2018 18:51:56]:agent:INFO: uname=Linux kali 3.10.65+ #1 SMP PREEMPT Sat Mar 5 08:46:58 CST 2016 aarch64
[02/Mar/2018 18:51:56]:agent:INFO: m2m=wss://m2m.dataplicity.com/m2m/
[02/Mar/2018 18:51:56]:agent:INFO: api=https://api.dataplicity.com/
[02/Mar/2018 18:51:56]:agent:INFO: serial=c8658908-57a9-40cc-b17f-62ee73e30365
[02/Mar/2018 18:51:56]:agent:INFO: poll=60
[02/Mar/2018 18:51:56]:m2m:ERROR: unhandled error from websocket
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.pex/install/dataplicity-0.4.30a0-py2-none-any.whl.1c3b34b697e73c7262620960a2cc191ffcde2c87/dataplicity-0.4.30a0-py2-none-any.whl/dataplicity/m2m/wsclient.py", line 265, in run
    log.exception('error handling websocket event')
  File "/data/data/com.termux/files/home/.pex/install/lomond-0.1.12-py2.py3-none-any.whl.ff11bc4bc36c40a4ce5d048ce8b289e3f32b74cd/lomond-0.1.12-py2.py3-none-any.whl/lomond/websocket.py", line 129, in __exit__
    self.session.close()
AttributeError: 'NoneType' object has no attribute 'close'
Exception in thread m2m:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/home/.pex/install/dataplicity-0.4.30a0-py2-none-any.whl.1c3b34b697e73c7262620960a2cc191ffcde2c87/dataplicity-0.4.30a0-py2-none-any.whl/dataplicity/m2m/wsclient.py", line 270, in run
    self.on_close()
AttributeError: 'WSClient' object has no attribute 'on_close'`

**Comment by lkdevil** [comment]
I m porting this to run on non pi system i hope all of you guys will help
Thnx in advance

**Comment by barfle** [comment]
Hi there,
May I ask what system you are porting this to?
Best,
Elliot.

**Comment by lkdevil** [comment]
Termux ( i m contributor of termux project )
But i dont know more about python 
and thnx for quick support

**Comment by barfle** [comment]
Cool.  We're probably a little limited in the programming time we could directly commit to it, but we're happy to support you with whatever information you require.

If memory serves that just looks like a networking error (ie no connection to internet, or the connection flaked out).  

You might find this helpful: https://docs.dataplicity.com/v1.0/docs/installation-on-different-oss

M.

**Comment by lkdevil** [comment]
I have one doubt .... supervisor is must ? Or i can just manually execute dataplicity binary file

**Comment by barfle** [comment]
Supervisor is just used to run the binary and keep it running.  You can substitute it for any alternative method of achieving the same.
