### ISSUE TITLE
Unable to connect to device. Please try again later.

### ISSUE THREAD

**Issue by alpapak** [wildfoundry/dataplicity-agent#97]
i am getting this error in log file

`Failed to find compatible interpreter on path /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin.

Examined the following working interpreters:
1.) /usr/bin/python2.7 CPython==2.7.16

Skipped the following broken interpreters:
1.) /usr/bin/python3.7:
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/dataplicity/.pex/isolated/a327c7699981cbbd93541ec65a30eb49c390cc09/pex/interpreter.py", line 22, in <module>
    from pex.dist_metadata import DistMetadata, Distribution, Requirement, RequirementParseError
  File "/home/dataplicity/.pex/isolated/a327c7699981cbbd93541ec65a30eb49c390cc09/pex/dist_metadata.py", line 25, in <module>
    from pex.pep_440 import Version
  File "/home/dataplicity/.pex/isolated/a327c7699981cbbd93541ec65a30eb49c390cc09/pex/pep_440.py", line 18, in <module>
    from pex.third_party.packaging import utils as packaging_utils
  File "/home/dataplicity/.pex/isolated/a327c7699981cbbd93541ec65a30eb49c390cc09/pex/vendor/_vendored/packaging/packaging/utils.py", line 9, in <module>
    from .tags import Tag, parse_tag
  File "/home/dataplicity/.pex/isolated/a327c7699981cbbd93541ec65a30eb49c390cc09/pex/vendor/_vendored/packaging/packaging/tags.py", line 7, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils.util'
2.) /usr/bin/python3.7m:
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/dataplicity/.pex/isolated/a327c7699981cbbd93541ec65a30eb49c390cc09/pex/interpreter.py", line 22, in <module>
    from pex.dist_metadata import DistMetadata, Distribution, Requirement, RequirementParseError
  File "/home/dataplicity/.pex/isolated/a327c7699981cbbd93541ec65a30eb49c390cc09/pex/dist_metadata.py", line 25, in <module>
    from pex.pep_440 import Version
  File "/home/dataplicity/.pex/isolated/a327c7699981cbbd93541ec65a30eb49c390cc09/pex/pep_440.py", line 18, in <module>
    from pex.third_party.packaging import utils as packaging_utils
  File "/home/dataplicity/.pex/isolated/a327c7699981cbbd93541ec65a30eb49c390cc09/pex/vendor/_vendored/packaging/packaging/utils.py", line 9, in <module>
    from .tags import Tag, parse_tag
  File "/home/dataplicity/.pex/isolated/a327c7699981cbbd93541ec65a30eb49c390cc09/pex/vendor/_vendored/packaging/packaging/tags.py", line 7, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils.util'

(See https://github.com/pantsbuild/pex/issues/1027 for a list of known breaks and workarounds.)

No working interpreter compatible with the requested constraints was found:

  A distribution for backports-ssl-match-hostname could not be resolved for /usr/bin/python2.7.
  Found 1 distribution for backports-ssl-match-hostname that do not apply:
  1.) The wheel tags for backports.ssl-match-hostname 3.4.0.2 are py3-none-any which do not match the supported tags of /usr/bin/python2.7:
  cp27-cp27mu-manylinux_2_28_armv7l
  ... 162 more ...
`
Tried remove device and reinstalled but nothing.

**Comment by alpapak** [comment]
sudo apt-get install python3-distutils

this fix my issue

**Comment by alpapak** [comment]
sudo apt-get install python3-distutils
