### ISSUE TITLE
Error on Ubuntu Server 24.04.1 LTS (RPI4): pex ImportError

### ISSUE THREAD

**Issue by JustAnEric** [wildfoundry/dataplicity-agent#98]
Fresh Ubuntu Server install with updated package lists and latest upgrades. Displayed on my Kali Linux instance also with fresh installs.
Ran on a Raspberry Pi 4.
Used the install agent provided on the Dataplicity website.

`sudo supervisorctl tail tuxtunnel` displays:
```
ort Version
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/pep_440.py", line 17, in <module>
    from pex.third_party import attr
ImportError: cannot import name 'attr' from 'pex.third_party' (/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/third_party/__init__.py)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88 in _run_code
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/__main__.py", line 85, in <module>
    from pex.pex_bootstrapper import bootstrap_pex
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/pex_bootstrapper.py", line 12, in <module>
    from pex.environment import ResolveError
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/environment.py", line 12, in <module>
    from pex import dist_metadata, pex_warnings, targets
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/dist_metadata.py", line 25, in <module>
    from pex.pep_440 import Version
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/pep_440.py", line 17, in <module>
    from pex.third_party import attr
ImportError: cannot import name 'attr' from 'pex.third_party' (/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/third_party/__init__.py)
```

From `cat /etc/os-release`: (not complete file)
```
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
```

From `sudo supervisorctl tail tuxtunnel`:
```
tuxtunnel        FATAL    Exited too quickly (process log may have details)
```

**Comment by GoldDominik893** [comment]
This must be a compatability issue with ubuntu 24.** or python as its the same for my setup. I recently updated my system to 24.10, and dataplicity stopped working. The logs seem to be the same.


`$ sudo supervisorctl tail tuxtunnel`:
```bash
ort Version
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/pep_440.py", line 17, in <module>
    from pex.third_party import attr
ImportError: cannot import name 'attr' from 'pex.third_party' (/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/third_party/__init__.py)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/__main__.py", line 85, in <module>
    from pex.pex_bootstrapper import bootstrap_pex
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/pex_bootstrapper.py", line 12, in <module>
    from pex.environment import ResolveError
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/environment.py", line 12, in <module>
    from pex import dist_metadata, pex_warnings, targets
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/dist_metadata.py", line 25, in <module>
    from pex.pep_440 import Version
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/pep_440.py", line 17, in <module>
    from pex.third_party import attr
ImportError: cannot import name 'attr' from 'pex.third_party' (/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/third_party/__init__.py)
```

`$ cat /etc/os-release`:
```bash
PRETTY_NAME="Ubuntu 24.10"
NAME="Ubuntu"
VERSION_ID="24.10"
VERSION="24.10 (Oracular Oriole)"
VERSION_CODENAME=oracular
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=oracular
LOGO=ubuntu-logo
```

**Comment by JustAnEric** [comment]
I ended up reverse-engineering Dataplicity's tuxtunnel service. If you guys still need a solution to this, please let me know!

**Comment by GoldDominik893** [comment]
Hi JustAnEric, thank you for making this. Unfortunately it doesn't work on my system when i ran your commands after the dataplicity install script ran (could be because its running 24.10 not 24.04). What would you suggest to get it to work again or should i just switch to ubuntu 22.04 lts?

Running `$ sudo supervisorctl tail tuxtunnel` returns the same errors as before:
```bash
ort Version
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/pep_440.py", line 17, in <module>
    from pex.third_party import attr
ImportError: cannot import name 'attr' from 'pex.third_party' (/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/third_party/__init__.py)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/__main__.py", line 85, in <module>
    from pex.pex_bootstrapper import bootstrap_pex
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/pex_bootstrapper.py", line 12, in <module>
    from pex.environment import ResolveError
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/environment.py", line 12, in <module>
    from pex import dist_metadata, pex_warnings, targets
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/dist_metadata.py", line 25, in <module>
    from pex.pep_440 import Version
  File "/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/pep_440.py", line 17, in <module>
    from pex.third_party import attr
ImportError: cannot import name 'attr' from 'pex.third_party' (/home/dataplicity/.pex/unzipped_pexes/0ead05278ab3d54afe6c974e5470f83061f0e860/.bootstrap/pex/third_party/__init__.py)
```

**Comment by toudi** [comment]
@GoldDominik893 could it be because you haven't edited the supervisor service file ? after the regular install, it would contain paths to the default installation of the agent however what @JustAnEric did is essentially cloning this repo and installing the agent from source into a separate directory. moreover, he is providing a template for systemd service rather than supervisor.

you have two options:

1/ update the service in `/etc/supervisor/conf.d/tuxtunnel.conf` and update the path
2/ remove supervisor altogether and use the provided systemd unit / service

**Comment by JustAnEric** [comment]
@toudi Yes, thank you for the clarification. The fix I provided does not use supervisorctl.

**Comment by Vixman** [comment]
Resolved in agent release v0.5.13

**Comment by JustAnEric** [comment]
That took a year ...
